// Code generated by file2byteslice. DO NOT EDIT.

package resources

var ConfigJson = []byte("{\r\n  \"screenWidth\": 640,\r\n  \"screenHeight\": 480,\r\n  \"title\": \"外星人入侵\",\r\n  \"bgColor\": {\r\n    \"r\": 230,\r\n    \"g\": 230,\r\n    \"b\": 230,\r\n    \"a\": 255\r\n  },\r\n  \"shipSpeedFactor\": 3,\r\n  \"bulletWidth\": 5,\r\n  \"bulletHeight\": 10,\r\n  \"bulletSpeedFactor\": 2,\r\n  \"bulletColor\": {\r\n    \"r\": 0,\r\n    \"g\": 0,\r\n    \"b\": 128,\r\n    \"a\": 255\r\n  },\r\n  \"maxBulletNum\": 10,\r\n  \"bulletInterval\": 50,\r\n  \"alienSpeedFactor\": 1,\r\n  \"titleFontSize\": 10,\r\n  \"fontSize\": 10,\r\n  \"smallFontSize\": 10\r\n}")
